Fix for the transformers translation plus some renaming
exasol/ai-lab pull request #162
Opened 2024-02-01 08:59 UTC by ahsimb

closes #160
closes #161

2024-02-01 09:31 UTC, ckunki requested changes

2024-02-01 09:31 UTC, ckunki commented on doc/changes/changes_0.1.0.md
Yesterday TK and me finally shipped somewhat like an initial release :rocket: :tada:.
Please 
* decide for a new version number, e.g.  0.2.0 or 1.0.0
*  increase the version number in file `pyproject.toml`.
* create a new changes file, e.g. `changes_0.2.0.md` or `changes_1.0.0.md` and move your additions there. 
*  update file `changelog.md`, too.

2024-02-01 09:31 UTC, ckunki commented on exasol/ds/sandbox/runtime/ansible/roles/jupyter/files/notebook/transformers/text_generation.ipynb
> +    "At the start, the `MY_TEXT` variable has an initial context. We will be updating and printing this variable at every call to the model.\n",
```suggestion
    "At the start, the `MY_TEXT` variable has an initial context. We will update and print this variable at every call to the model.\n",
```

2024-02-01 09:31 UTC, ckunki commented on exasol/ds/sandbox/runtime/ansible/roles/jupyter/files/notebook/transformers/sequence_classification.ipynb
> +    "We will save the result in the variable `udf_output` to perform automatic testing of this notebook."
```suggestion
    "We will save the result in the variable `udf_output` to support automatic testing of this notebook."
```

2024-02-01 09:31 UTC, ckunki commented on exasol/ds/sandbox/runtime/ansible/roles/jupyter/files/notebook/transformers/question_answering.ipynb
> +    "We will save the result in the variable `udf_output` to perform automatic testing of this notebook."
```suggestion
    "We will save the result in the variable `udf_output` to support automatic testing of this notebook."
```

2024-02-01 09:31 UTC, ckunki commented on exasol/ds/sandbox/runtime/ansible/roles/jupyter/files/notebook/transformers/masked_modelling.ipynb
> +    "We will save the result in the variable `udf_output` to perform automatic testing of this notebook."
```suggestion
    "We will save the result in the variable `udf_output` to support automatic testing of this notebook."
```

2024-02-01 09:31 UTC, ckunki commented on exasol/ds/sandbox/runtime/ansible/roles/jupyter/files/notebook/transformers/token_classification.ipynb
> +    "Let's run the token classification model. We will save the result in the variable `udf_output` to perform automatic testing of this notebook."
```suggestion
    "Let's run the token classification model. We will save the result in the variable `udf_output` to support automatic testing of this notebook."
```

2024-02-01 09:31 UTC, ckunki commented on exasol/ds/sandbox/runtime/ansible/roles/jupyter/files/notebook/transformers/translation.ipynb
> +    "Let's run the translation model. We will save the result in the variable `udf_output` to perform automatic testing of this notebook."
```suggestion
    "Let's run the translation model. We will save the result in the variable `udf_output` to support automatic testing of this notebook."
```

2024-02-01 09:31 UTC, ckunki commented on exasol/ds/sandbox/runtime/ansible/roles/jupyter/files/notebook/transformers/zero_shot_classification.ipynb
> +    "Let's run the zero shot text classification model. We will save the result in the variable `udf_output` to perform automatic testing of this notebook."
```suggestion
    "Let's run the zero shot text classification model. We will save the result in the variable `udf_output` to support automatic testing of this notebook."
```

2024-02-01 09:31 UTC, ckunki commented on exasol/ds/sandbox/runtime/ansible/roles/jupyter/files/notebook/utils/main_config_ui.ipynb
> +    "    Creates a UI form for choosing between the Exasol Docker-DB and an external Exasol Database.\n",
:+1:

2024-02-01 09:44 UTC, tkilias commented on doc/changes/changes_0.1.0.md
0.1.1 or 0.2.0 are next, the 1.0.0 will be end of the month

2024-02-01 16:21 UTC, ahsimb commented
JupySQL's official documentation is inadequate. 
I think it's good to have the --save option for two reasons. Firstly, it could be helpful for the user. It works like the `WITH` clause. You can use the saved result as a table. Secondly, inserting it during a test will be too hacky for my liking. It will limit the format of the query to a certain pattern. On the other hand, if we don't mention the test the user might decide that she doesn't need it and delete it for better clarity.

2024-02-02 07:35 UTC, tkilias approved these changes

2024-02-02 07:42 UTC, ckunki approved these changes

2024-02-02 07:42 UTC, merged