Refactoring/#258 used a non root user to run jupyter in the docker image ai lab
exasol/ai-lab pull request #231
Opened 2024-02-26 10:03 UTC by ckunki

Closes #258

2024-02-27 13:43 UTC, ckunki commented on exasol/ds/sandbox/lib/dss_docker/create_image.py
> +        try:
I added these lines to speed up testing Ansible tasks

2024-02-27 13:52 UTC, ckunki commented on exasol/ds/sandbox/lib/dss_docker/create_image.py
> +            pass
I added these lines to speed up testing Ansible tasks

2024-02-27 13:52 UTC, ckunki commented on exasol/ds/sandbox/runtime/ansible/general_setup_tasks.yml
> +  # should folder /root be replaced by {{ user_home }} ?
Currently I did not find such a directory at all.

2024-02-27 13:52 UTC, ckunki commented on exasol/ds/sandbox/runtime/ansible/roles/jupyter/tasks/pip-install.yml
This file originally was named `install-pip-packages.yml`.

Additionally, I renamed some of the variables in this file and fixed an Ansible warning about 
providing a list of dictionaries to vars: See https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_8.html#deprecated

2024-02-27 15:01 UTC, tkilias requested changes

2024-02-28 14:06 UTC, tkilias requested changes

2024-02-28 14:06 UTC, tkilias commented on test/codebuild/test_ci.py
> +            # probably we need to set the password for user "jupyter" here.
Not necessary anymore

2024-02-28 14:06 UTC, tkilias commented on test/integration/test_create_dss_docker_image.py
> +@pytest.mark.skipif(os.environ.get('DSS_RUN_CI_TEST') != 'true',
Why is this needed?

2024-02-28 14:06 UTC, tkilias commented on test/integration/test_motd_jupyter_template.py
> +    # jupyterlab_config_json
Comment necessary

2024-02-29 09:51 UTC, tkilias commented on exasol/ds/sandbox/runtime/ansible/roles/jupyter/templates/etc/update-motd.d/999-jupyter
> +To update the password as user {{ user_name }} run
```suggestion
To update the password run as user {{ user_name }} the following command
```

or should we directly show it with sudo

2024-02-29 10:05 UTC, tkilias approved these changes

2024-02-29 13:28 UTC, merged