Check if the docker socket is mounted.
exasol/ai-lab pull request #238
Opened 2024-02-29 17:45 UTC by ahsimb

closes #199

2024-02-29 18:32 UTC, tkilias requested changes

2024-02-29 18:32 UTC, tkilias commented on exasol/ds/sandbox/runtime/ansible/roles/jupyter/files/notebook/utils/useful_urls.ipynb
short question, you are aware that you can also import local python files, you don't always need notebooks

2024-02-29 18:32 UTC, tkilias commented on exasol/ds/sandbox/runtime/ansible/roles/jupyter/files/notebook/utils/main_config_ui.ipynb
this code gets uncomfortable big, I think, we should think about, how we can extract it into the notebook-connector and do there proper ui testing. Besides ui testing, we could also mock the widget creation and check, if we create them with the correct content.

2024-03-01 08:08 UTC, ahsimb commented on exasol/ds/sandbox/runtime/ansible/roles/jupyter/files/notebook/utils/main_config_ui.ipynb
Not sure about the UI testing. Anyway, I certainly don't want to do this in the scope of this ticket.

2024-03-01 08:57 UTC, tkilias commented on exasol/ds/sandbox/runtime/ansible/roles/jupyter/files/notebook/utils/main_config_ui.ipynb
yes, that was only a general observation.

2024-03-18 08:14 UTC, kaklakariada approved these changes

2024-03-18 08:15 UTC, tkilias approved these changes

2024-03-18 08:15 UTC, merged